packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  jiti: ^2.5.0
catalogs:
  cli:
    '@antfu/eslint-config': ^4.19.0
    '@antfu/ni': ^25.0.0
    bumpp: ^10.2.0
    eslint: ^9.31.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    unbuild: ^3.6.0
    vite: ^7.0.6
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.0
  types:
    '@types/node': ^24.1.0
  utils:
    tinyexec: ^1.0.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
