shellEmulator: true

trustPolicy: no-downgrade

catalogs:
  cli:
    '@antfu/eslint-config': ^7.7.3
    '@antfu/ni': ^30.0.0
    bumpp: ^11.0.1
    eslint: ^10.1.0
    lint-staged: ^16.4.0
    simple-git-hooks: ^2.13.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^8.0.3
  testing:
    vitest: ^4.1.2
    vitest-package-exports: ^1.2.0
    yaml: ^2.8.3
  types:
    '@types/node': ^24.12.0
  utils:
    tinyexec: ^1.0.4
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
